name: "Configure Java and Gradle"
description: "Boilerplate steps"
runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2