name: Generate Release Tag and Publish Artifacts

on:
  push:
    branches:
      - main

jobs:
  # Generates a new tag and pushes it
  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          chmod +x .github/scripts/tag.sh
          ./.github/scripts/tag.sh

  # Publishes everything
  publish:
    runs-on: ubuntu-latest
    needs:
      - generate-tag
    strategy:
      fail-fast: true
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: Version Name
        uses: ./.github/actions/version-name
        with:
          # Sonatype Credentials
          ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ossrh_password: ${{ secrets.OSSRH_PASSWORD }}

          # Sign Credentials
          sign_key_id: ${{ secrets.SIGN_KEY_ID }}
          sign_password: ${{ secrets.SIGN_PASSWORD }}

      - name: Build
        run: ./gradlew :easy-nfc:assembleRelease

      - name: Publish
        run: ./gradlew :easy-nfc:publishLibPublicationToSonatypeReleaseRepository