name: Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
      - 'feature/**'
      - 'bugfix/**'
      - 'config/**'
    paths:
      - '**.kt'
      - '**.gradle'
    types:
      - synchronize
      - opened
      - reopened
      - ready_for_review

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: Lint
        run: ./gradlew :easy-nfc:lint

      - name: Detekt
        run: ./gradlew :easy-nfc:detekt

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: Unit Tests
        run: ./gradlew :easy-nfc:testDebugUnitTest --no-parallel

      - name: Kover
        run: ./gradlew :easy-nfc:koverVerify

  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: Assemble
        run: ./gradlew :easy-nfc:assembleRelease